version: '3.7'

networks:
   app:
      name: app
      driver: bridge

services:
   mysql:
      image: mysql
      container_name: mysql
      build: /home/docker-compose/mysql/
      volumes:
       - database:/var/lib/mysql/
      networks:
       - app
      restart: always
   php:
      image: php
      container_name: php
      build: /home/docker-compose/php_fpm/
      volumes:
         - php:/var/www/html/
      networks:
         - app
      depends_on:
         - mysql
      restart: always
   nginx:
      image: nginx
      container_name: nginx
      build: /home/docker-compose/nginx/
      depends_on:
         - php
      volumes:
         - php:/var/www/html/
      networks:
         - app
      ports:
       - "443:443"
       - "80:80"
      restart: always

volumes:
   php:
      name: php
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /home/docker-compose/www_data/php
   database:
      name: database
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /home/docker-compose/www_data/database