---
- name: apt-get update
  apt:
    update_cache: yes

- name: install packeges
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: add official GPG key docker
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower}}/gpg

- name: docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower}} {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: install docker
  apt:
    name: "{{ item }}"
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - docker
    - docker-compose

- name: service start
  systemd:
    name: docker.service
    state: started
    daemon_reexec: true
    enabled: true